excluded:
    - Frameworks
    - Pods
    - Carthage/
    - CodeGeneration/Generated
    - fastlane/
    - "*.generated.swift"
    - vendor/
    - Carthage

disabled_rules:
    - function_parameter_count
    - line_length
    - identifier_name
    - type_name
    - force_unwrapping

opt_in_rules:
    - anyobject_protocol
    - array_init
    - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - collection_alignment, avec align_colons à true
    - comma
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - discouraged_object_literal
    - empty_collection_literal
    - empty_count
    - empty_string
    - enum_case_associated_values_count
    - explicit_init
    - fatal_error_message
    - file_length
    - first_where
    - force_unwrapping
    - last_where
    - legacy_random
    - literal_expression_end_indentation
    - modifier_order
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - operator_usage_whitespace
    - overridden_super_call
    - override_in_extension
    - private_action
    - private_outlet
    - redundant_nil_coalescing
    - sorted_first_last
    - toggle_bool
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - yoda_condition


first_where: error
last_where: error
sorted_first_last: error

fatal_error_message: error
file_length:
    ignore_comment_only_lines: true

function_body_length:
    warning: 100
    error: 150

force_cast: warning
force_try: warning

modifier_order:
    preferred_modifier_order: ['required', 'override', 'acl', 'setterACL', 'final', 'dynamic', 'mutators', 'lazy', 'convenience', 'typeMethods', 'owned']

number_separator:
    minimum_length: 5
    minimum_fraction_length: 999999
