name: Swift

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: App-BDE-iOS.xcodeproj
        scheme: App-BDE-iOSTests
        action: test
